local_path: '/path/to/working/directory/'
training_set_name: '_model_name'
training_set_path: '/path/to/train_tce_csv_file.csv'
test_set_path: '/path/to/test_tce_csv_file.csv'
rateval: 0.2
learning_rate: 0.001
batch_size: 128
num_epochs: 50
num_classes: 1
save_features: False
features_filename: '/path/to/output/directory/'
cbn: 5
cfs: 3
cbff: 2
psz: 5
pst: 2
fc_layers_num: 1
fc_units: 512
fc_output_size: 1
plot_dir: '/path/to/output/directory/'
prcurve_filename: ''
roc_curve_filename: ''
